import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useIntl } from 'react-intl';
import styles from '@/assets/styles/Home.module.css';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { selectPost } from '@/redux/slices/postSlice';
import { ICO } from '@/services/postApi';
import { GetPostAction } from '@/redux/actions/PostAction';

const Home: NextPage = () => {
  const { locales } = useRouter();
  const intl = useIntl();
  const dispatch = useAppDispatch();
  const posts = useAppSelector(selectPost);
  return (
    <div className={styles.container}>
      <Head>
        <title>
          {/* <FormattedMessage id="about" /> */}
          {intl.formatMessage({ id: 'page.home.head.title' })}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main_local}>
        <header>
          <div className={styles.languages}>
            {[...(locales as Array<string>)].sort().map((locale) => (
              <Link key={locale} href="/" locale={locale}>
                {locale}
              </Link>
            ))}
          </div>
        </header>
        <h1 className={styles.title}>
          {/* <FormattedMessage id="about" /> */}
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          {intl.formatMessage({ id: 'page.home.head.meta.description' })}
        </h1>
        <button onClick={() => dispatch(GetPostAction())}>Get post</button>
        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {posts.map((post: ICO) => (
            <a key={post.id} href="https://nextjs.org/docs" className={styles.card}>
              <h2>{post.title}</h2>
              <p>{post.body}</p>
            </a>
          ))}

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
